on:
  push: {}
  pull_request:
    types: 
      - labeled
  issues:
    types:
      - labeled
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: WillAbides/exampleaction@master
      with:
        allow_first_release: "true"
    # Use the output from the `hello` step
    - name: the output
      run: echo "The output was ${{ steps.hello.outputs.next_version }}"
